### ISSUE TITLE
Consider colocation of version and change notes in release TOML

### ISSUE THREAD

**Issue by rtsao** [publisher/publisher#27]
Especially with many packages, it can be burdensome to have separate release notes and release versions in separate files.

Potentially, the notes markdown could be colocated within the TOML:

````toml

["@publisher/probot-app"]
# prior : "0.1.8"
version = "0.1.9"
notes = """
- Arbitrary markdown
- Goes here

## Migration guide

```diff
+ foo
- bar
```

Hello world

"""

````

This might be convenient, although an obvious drawback is Markdown preview is lost. However, this could be addressed through a different render preview via some separate app.

This app could show the even more accurate release notes preview (including the various markdown transforms performed by the bot).
